# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version:
          - '1.22'
          - '1.23'

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true

      - run: |
          go build ./...
